export const formData: {
    type: string,
    name: string,
    label: string,
    placeholder: string,
    icon: string,
    keyboardType: string,
    autoFocus: boolean,
}[] = [
    {
        type: 'tel',
        name: 'phone',
        label: 'Enter your mobile number',
        placeholder: 'Enter mobile number',
        icon: 'call',
        keyboardType: 'phone-pad',
        autoFocus: true,
    },
    {
        type: "email",
        name: 'email',
        label: "What's your email?",
        placeholder: 'name@example.com',
        icon: 'email',
        keyboardType: 'email-address',
        autoFocus: true,
    },
    {
        type: "password",
        name: 'password',
        label: 'Create your account password',
        placeholder: 'Enter password',
        icon: 'lock',
        keyboardType: 'password-visible',
        autoFocus: true,
    },
    {
        type: "date",
        name: 'birthdate',
        label: 'When is your birthday?',
        placeholder: '01/01/1990',
        icon: 'today',
        keyboardType: 'number-pad',
        autoFocus: true,
    },
    {
        type: "text",
        name: 'residence',
        label: 'Pin your residence location',
        placeholder: '1800 example st',
        icon: 'home',
        keyboardType: 'default',
        autoFocus: true,
    }
];
